AppBundle\Entity\Video:
  type: entity
  table: null
  repositoryClass: AppBundle\Repository\VideoRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
    comment:
      type: text

  oneToOne:
    media:
      targetEntity: AppBundle\Entity\Media
      cascade: ['all']
  lifecycleCallbacks: {  }